### ISSUE TITLE
Load DLL/EXE from memory

### ISSUE THREAD

**Issue by soloist-v** [IsaacMarovitz/pe-parser#1]
Hello, can you add the ability to load DLL/EXE from memory, and also provide access to the public functions of the DLL/EXE?

**Comment by IsaacMarovitz** [comment]
I'm not entirely sure what you mean by load from memory. Currently, the parser works on portable executables in the form of a `[u8]` byte array. As long as your PE is loaded into memory in that form, you can parse it.

If you mean loading a PE *into* memory as in to start execution, that's beyond the scope of this project, but I do want to take a look at that later down the line in a different project.

**Comment by soloist-v** [comment]
I actually want to execute the PE in memory and I'm looking forward to the new project you mentioned.
