### ISSUE TITLE
Usage with nostd

### ISSUE THREAD

**Issue by WhyNotHugo** [IsaacMarovitz/pe-parser#10]
I'd like to use this library in a `nostd` program.

My code will run in a UEFI environment, so it has to be `nostd` and is a `PE/COFF` binary file. I mostly want to use [pe_parser::pe::parse_portable_executable](https://docs.rs/pe-parser/0.3.1/pe_parser/pe/fn.parse_portable_executable.html) to find the offset of a few sections

I think a sane approach would be to add an `std` feature flag (which is enabled by default to avoid breaking existing usages).

The main breaking change that I can see is that `parse_portable_executable` returns `std::io::Error`. The only way around this is to use a custom error type. This shouldn't be too hard to pull off, since there's not that many scenarios where `std::io::Error` is used (and many usages are just `ErrorKind::Other`, so a cusotm error type might actually improve the API a bit).

Obviously the `main` function would not work on `nostd`; only the library aspect of this crate.

**Comment by WhyNotHugo** [comment]
I guess the real question here is: are you okay with changing the main usage of `std::io::Error` for a custom Error type?

I have a WIP branch for making nostd optional, but that would be the main breaking change.

**Comment by WhyNotHugo** [comment]
I think https://github.com/WhyNotHugo/pe-parser/commits/nostd does it.

**Comment by IsaacMarovitz** [comment]
> I think https://github.com/WhyNotHugo/pe-parser/commits/nostd does it.

Code looks good! Feel free to PR it if you want.

**Comment by WhyNotHugo** [comment]
So far I'm not convinced about the (somewhat verbose) error implementation. I'm thinking of using `thiserror` instead.

**Comment by IsaacMarovitz** [comment]
> thiserror

I'm not sure that crate supports `nostd`

**Comment by WhyNotHugo** [comment]
Good point; it doesn't.
