### ISSUE TITLE
vma from pe-parser does not match vma from objdump

### ISSUE THREAD

**Issue by Lunarequest** [IsaacMarovitz/pe-parser#32]
I'm currently trying to use pe-parser to get section headers from the systemd efi stub(all uefi executables are pe exectuables) however when I try and get the vma it doesn't match what comes from objdump which is what i require. 

`objdump -h` (only output headers) gives the following output

```

/usr/lib/systemd/boot/efi/linuxx64.efi.stub:     file format pei-x86-64

Sections:
Idx Name          Size      VMA               LMA               File off  Algn
  0 .text         0000fcdf  000000014df91000  000000014df91000  00000400  2**4
                  CONTENTS, ALLOC, LOAD, READONLY, CODE
  1 .rodata       000029d4  000000014dfa1000  000000014dfa1000  00010200  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
  2 .data         000002d8  000000014dfa4000  000000014dfa4000  00012c00  2**4
                  CONTENTS, ALLOC, LOAD, DATA
  3 .sdmagic      00000027  000000014dfa5000  000000014dfa5000  00013000  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
  4 .sbat         000000cb  000000014dfa6000  000000014dfa6000  00013200  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
  5 .reloc        00000080  000000014dfa7000  000000014dfa7000  00013400  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
```
we want the last part reloc, which makes size and vma 128, 5603225600 respectively in rust the code i came up with is
```rust
if !systmd_stub.exists() {
        return Err(anyhow!(
            "the efi stub {} does not exist",
            systmd_stub.display()
        ));
    }

    let bin = read(systmd_stub)?;
    let parse = parse_portable_executable(&bin)?;
    let sections = parse.section_table;
    let reloc = match sections.last() {
        Some(header) => header,
        None => {
            return Err(anyhow!("unable to parse systemd efi stub"));
        }
    };

   println!("{}\n{}",reloc.virtual_address, reloc.virtual_size);
```
the output given is `94208` and `128` which means the VMA is wrong. I'm a bit  lost why the vma is so different.

**Comment by IsaacMarovitz** [comment]
Can you provide the PE files you're trying to parse here

**Comment by Lunarequest** [comment]
I was trying to parse the pe from systemd you can find a version here https://archlinux.org/packages/core/x86_64/systemd/download/ it will be in the directory usr/lib/systemd/boot/efi/

**Comment by IsaacMarovitz** [comment]
<img width="343" alt="Screenshot 2023-10-10 at 12 03 08" src="https://github.com/IsaacMarovitz/pe-parser/assets/42140194/d4ab0860-eaec-4a3d-8bbd-98492637b9c2">
This is what I see in Binary Ninja, which doesn't seem to match either

**Comment by IsaacMarovitz** [comment]
<img width="437" alt="Screenshot 2023-10-10 at 12 07 48" src="https://github.com/IsaacMarovitz/pe-parser/assets/42140194/3f81a78e-ebaa-4b47-bf40-d1e3562d19e8">

This is what I see in Binary Ninja for `linuxx64.efi.stub` downloaded from that link

**Comment by IsaacMarovitz** [comment]
<img width="350" alt="Screenshot 2023-10-10 at 12 14 04" src="https://github.com/IsaacMarovitz/pe-parser/assets/42140194/17be9639-c8fc-400c-92ab-1bb8e849f37d">

Matches what I see in PE Parser

**Comment by IsaacMarovitz** [comment]
Here's what Virtual Address means from MS Docs:
> For executable images, the address of the first byte of the section relative to the image base when the section is loaded into memory.

0x000000014dfa7000 - 0x13000 = 0x14DF94000 which AFAIK is the image base, although Binary Ninja I think is using a base of 0x14DF90000

**Comment by IsaacMarovitz** [comment]
<img width="270" alt="Screenshot 2023-10-10 at 12 28 10" src="https://github.com/IsaacMarovitz/pe-parser/assets/42140194/a5b0d01e-2949-475d-aca1-db0d1820e710">

Yes that's the image base

**Comment by IsaacMarovitz** [comment]
So apart from that 0x4000 difference, the VMA you're looking for will be the Image Base + Virtual Address
